[package]
name = "compiler"
version = "0.1.0"
authors = ["Muriel Berehulka <murielberehulka@hotmail.com>"]
edition = "2021"

[dependencies]
wgpu = "0.12"
bytemuck = { version = "1.8", features = ["derive"] }